### ISSUE TITLE
Krona db update optional

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/PikaVirus_OLD#2]
This process should be optional and off by default.
https://github.com/BU-ISCIII/PikaVirus/blob/36889720bbb17956541dbffa9b2246dd2f2d8dfd/main.nf#L716

**Comment by GuilleGorines** [comment]
Unfortunately, krona needs the files generated by the process:

``` 
Taxonomy not found in /work/conda/nf-core-pikavirus-1.0dev-c05eefeaf45ba65935ce203d9b071fbd/opt/krona/taxonomy. 
Was updateTaxonomy.sh run? 
at work/conda/nf-core-pikavirus-1.0dev-c05eefeaf45ba65935ce203d9b071fbd/opt/krona/scripts/../lib/KronaTools.pm line 1540.
```

I'm afraid we cannot omit that step, at least by now.
