### ISSUE TITLE
Change where sam to bam is performed

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/PikaVirus_OLD#3]
Consider adding this to bowtie process as a pipe so sam files are not stored and we save space and generate less processes:
https://github.com/BU-ISCIII/PikaVirus/blob/36889720bbb17956541dbffa9b2246dd2f2d8dfd/main.nf#L942-L948

**Comment by saramonzon** [comment]
same here
https://github.com/BU-ISCIII/PikaVirus/blob/5505a52a7d95441f9517dc2c393a9140903ffc4b/main.nf#L561-L567

**Comment by GuilleGorines** [comment]
Fixed on 7fef4230bb0c30de2501593fb0e7cb731f2a3625 along with other issues!
