### ISSUE TITLE
Samtools mpileup in ivar process

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/PikaVirus_OLD#4]
Move mpileup to ivar process, only mv inside the if.
https://github.com/BU-ISCIII/PikaVirus/blob/5505a52a7d95441f9517dc2c393a9140903ffc4b/main.nf#L961-L985

**Comment by GuilleGorines** [comment]
Fixed on 7fef4230bb0c30de2501593fb0e7cb731f2a3625!
